spring:
  datasource:
    url: jdbc:h2:file:./db/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto :  update
  h2:
    console:
      enabled: true
      path: /h2_console

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 55MB

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

auth:
  jwtSecret: jwtSecretKey
  jwtExpiration: 86400


file:
  upload-dir: ./uploads

time:
  in:
    milliseconds: 86400000

security:
  oauth2:
    client:
      clientId: 697750161220-pt2vbi2n7g4689g81f95m9gijsesljm4.apps.googleusercontent.com
      clientSecret: 9oDJjyhp4cxsvHXZHHysqaxL
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid, email, profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true