spring:
  datasource:
    url: jdbc:h2:file:./db/testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto :  none
      generate-ddl: false

  h2:
    console:
      enabled: true
      path: /h2_console

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 55MB

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect

auth:
  jwtSecret: jwtSecretKey
  jwtExpiration: 86400


file:
  upload-dir: ./uploads

time:
  in:
    milliseconds: 86400000

