CREATE  TABLE IF NOT EXISTS USER(
    ID BIGINT auto_increment primary key not null,
    ACTIVATION_CODE VARCHAR(255),
    NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PASSWORD VARCHAR(500),
    USERNAME VARCHAR(20),
    ADRESS VARCHAR(255),
    DATE_OF_BIRTH DATE
);

CREATE  TABLE IF NOT EXISTS ROLE(
    ID BIGINT auto_increment primary key not null,
    NAME VARCHAR(20)
);

CREATE  TABLE IF NOT EXISTS USER_ROLE(
    ID_USER BIGINT primary key not null,
    ID_ROLE BIGINT
);

CREATE TABLE IF NOT EXISTS CATALOG_OF_OPERATION_MODE(
    ID BIGINT auto_increment primary key,
    OPERATION_MODE VARCHAR(20)
);

CREATE  TABLE IF NOT EXISTS COOPERATION_CONTRACT(
    ID BIGINT auto_increment primary key not null,
    CLIENT_FULL_NAME VARCHAR(100),
    CLIENT_ADRESS VARCHAR(255),
    DATE_OF_CREATION DATE,
    LAST_CHANGE TIMESTAMP,
    OTHER_INFO VARCHAR(1000),
    CLIENT_RESPONSIBILITY VARCHAR(1000),
    CREATOR_RESPONSIBILITY VARCHAR(1000),
    KIND_OF_ACTIVITY VARCHAR(100),
    TERM INTEGER,
    TERMINATION_CONDITIONS VARCHAR(1000),
    ID_USER BIGINT,
    IS_ACTIVE BOOLEAN NOT NULL,
    TITLE VARCHAR(100),
    FILENAME VARCHAR(255)
);

CREATE  TABLE IF NOT EXISTS RENTAL_CONTRACT(
    ID BIGINT auto_increment primary key not null,
    CLIENT_ADRESS VARCHAR(255),
    CLIENT_FULL_NAME VARCHAR(100),
    DATE_OF_CREATION DATE,
    IS_ACTIVE BOOLEAN NOT NULL,
    LAST_CHANGE TIMESTAMP,
    OTHER_INFO VARCHAR(1000),
    TITLE VARCHAR(100),
    END_RENTAL DATE,
    RENTAL_OBJECT VARCHAR(100),
    RENTAL_PRICE INTEGER,
    START_RENTAL DATE,
    ID_USER BIGINT,
    FILENAME VARCHAR(255)
);

CREATE  TABLE IF NOT EXISTS CREDIT_CONTRACT(
    ID BIGINT auto_increment primary key not null,
    CLIENT_ADRESS VARCHAR(255),
    CLIENT_FULL_NAME VARCHAR(100),
    DATE_OF_CREATION DATE,
    LAST_CHANGE TIMESTAMP,
    OTHER_INFO VARCHAR(1000),
    ANNUAL_INTEREST FLOAT,
    CREDIT_AMOUNT FLOAT,
    TERM INTEGER,
    ID_USER BIGINT,
    IS_ACTIVE BOOLEAN NOT NULL,
    TITLE VARCHAR(100),
    FILENAME VARCHAR(255)
);

CREATE  TABLE IF NOT EXISTS CONTRACT_OF_SALE(
    ID BIGINT auto_increment primary key not null,
    CLIENT_ADRESS VARCHAR(255),
    CLIENT_FULL_NAME VARCHAR(100),
    DATE_OF_CREATION DATE,
    LAST_CHANGE TIMESTAMP,
    OTHER_INFO VARCHAR(1000),
    SALE_OBJECT VARCHAR(100),
    SALING_PRICE FLOAT,
    WARRANTY_PERIOD INTEGER,
    ID_USER BIGINT,
    IS_ACTIVE BOOLEAN NOT NULL,
    TITLE VARCHAR(100),
    FILENAME VARCHAR(255)
);

CREATE  TABLE IF NOT EXISTS WORK_CONTRACT(
    ID BIGINT auto_increment primary key not null,
    CLIENT_ADRESS VARCHAR(255),
    CLIENT_FULL_NAME VARCHAR(100),
    DATE_OF_CREATION DATE,
    LAST_CHANGE TIMESTAMP,
    OTHER_INFO VARCHAR(1000),
    HOLIDAY INTEGER,
    POSITION VARCHAR(100),
    PLACE_OF_WORK VARCHAR(100),
    SALARY INTEGER,
    START_WORK DATE,
    WORKING_HOURS INTEGER,
    ID_USER BIGINT,
    ID_OPERATION_MODE BIGINT,
    IS_ACTIVE BOOLEAN NOT NULL,
    TITLE VARCHAR(100),
    TERM INTEGER,
    FILENAME VARCHAR(255)
);



ALTER TABLE USER ADD CONSTRAINT if not exists UKSB8BBOUER5WAK8VYIIY4PF2BX UNIQUE(USERNAME);
ALTER TABLE USER ADD CONSTRAINT if not exists UKOB8KQYQQGMEFL0ACO34AKDTPE UNIQUE(EMAIL);

ALTER TABLE USER_ROLE ADD CONSTRAINT if not exists FK2AAM9NT2TV8VCFYMI3JO9C314 FOREIGN KEY(ID_ROLE) REFERENCES ROLE(ID) ;
ALTER TABLE USER_ROLE ADD CONSTRAINT if not exists FKFHXAAEL2M459KBK8LV8SMR5IV FOREIGN KEY(ID_USER) REFERENCES USER(ID) ;

ALTER TABLE WORK_CONTRACT ADD CONSTRAINT if not exists FKP4UGCK9D6FARQFSXARYK3W5C8 FOREIGN KEY(ID_USER) REFERENCES USER(ID) ;
ALTER TABLE WORK_CONTRACT ADD CONSTRAINT if not exists FKOONE504PTN740UQ08DTPF6UVA FOREIGN KEY(ID_OPERATION_MODE) REFERENCES CATALOG_OF_OPERATION_MODE(ID) ;

ALTER TABLE RENTAL_CONTRACT ADD CONSTRAINT if not exists FK40X0NMXO7QJG4307QT0BI3U1P FOREIGN KEY(ID_USER) REFERENCES USER(ID) ;

ALTER TABLE CREDIT_CONTRACT ADD CONSTRAINT if not exists FK43NNMP046VOJY2RX1IEGTJWYO FOREIGN KEY(ID_USER) REFERENCES USER(ID) ;

ALTER TABLE COOPERATION_CONTRACT ADD CONSTRAINT if not exists FKS27E4BF2NGS766N8UXLLT7MX0 FOREIGN KEY(ID_USER) REFERENCES USER(ID) ;

ALTER TABLE CONTRACT_OF_SALE ADD CONSTRAINT if not exists FK2QPN7NQULNQG78OIQU9Y5XAAB FOREIGN KEY(ID_USER) REFERENCES USER(ID) ;

